name: Tweet Fetcher

on:
  schedule:
    #- cron: '0 14-22 * * *'
    #- cron: '0 6 * * *'
    - cron: '0 * * * *'
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  

jobs:
  get-tweet:
    name: ğŸ¦ Main Job
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ğŸ§° Install dependency
        run: pip install twikit

      - name: ğŸª Decode cookies
        run: echo "${{ secrets.TWITTER_COOKIES_B64 }}" | base64 -d > badeline.json

      - name: ğŸ•’ Wait up to 10s
        run: |
          sleep $((RANDOM % 5 + 5))

      - name: ğŸ“©âœï¸ Fetch & write
        run: python main.py

      - name: ğŸ“¤ Commit latest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add badeline.txt
          git commit -m "chore: update latest tweet :3" || echo "no changes"
          git push
